### ISSUE TITLE
Depreciated packages causing error in local setup 

### ISSUE THREAD

**Issue by ruddi10** [anitab-org/open-source-programs-backend#116]
### Describe the bug
I found that some of the packages in the requirements.txt are depreciated leading to error while trying to intall them on setup

### To Reproduce
1. Clone the repo 
2. Then create a virtual environment (Advisable)
3. Then run pip install -r requirements.txt
4. See the error

### Expected behavior
It was expected that all the packages get sucessfully installed.

### Screenshots

![Screenshot from 2021-03-08 12-11-02](https://user-images.githubusercontent.com/56596436/110284870-6656f280-8008-11eb-8eb4-8433ac9eafc0.png)

### Desktop (please complete the following information):
 - OS: Linux
 - Browser Mozilla
 - Version 84.0.2

**Comment by ruddi10** [comment]
@isabelcosta  @codesankalp @Aaishpra  kindly assign this issue to me

**Comment by Aaishpra** [comment]
Can you try running the project without creating virtual environment on the terminal.

**Comment by codesankalp** [comment]
Hey @ruddi10, This issue is related to pip and python. For now, there are no deprecated packages in requirements.txt.
According to your error building wheel for psycopg2 fails.
Try this:
```
pip install --upgrade wheel
pip install --upgrade setuptools
pip install -r requirements.txt
```
NOTE:- Try the above commands after creating and activating virtual env.

So, I am closing this issue.
If you have another point regarding this issue feel free to reopen it or ask your questions in Zulip. :relaxed:

**Comment by ruddi10** [comment]
@codesankalp I dont think its a very good approach requirements should work without prerequisites. I think upgrading packages is neccessary.

**Comment by codesankalp** [comment]
Which packages are you going to upgrade @ruddi10?
So that this issue will be solved.
As far as I know this error is related to python and pip and didn't require dependency update.

**Comment by ruddi10** [comment]
psycopg2,pylint,astroid @codesankalp

**Comment by ruddi10** [comment]
I have solved this issue on my local development environment by doing so and its working fine just waiting for your approval to fix it.

**Comment by codesankalp** [comment]
Can you comment on the content of your requirements.txt here @ruddi10?
pylint will be deleted in the future as flake8 is the current linter.
And astroid version is the default version recommended by Django and I don't suggest changing it manually.
Is changing the version of psycopg2 solved your problem?

**Comment by ruddi10** [comment]
Yup those two were additional error that happened due to pylint depreeated version

**Comment by ruddi10** [comment]
The screenshot of the error that I have posted will b solved by updating the psycopg2 package other two are not neccessary @codesankalp

**Comment by ruddi10** [comment]
Like once you willl solve the above issue and rerun the requirements file once more error will be thrown due to depreceated version of pylint and that version requires newer version of astroid thats why I changed those too also

**Comment by codesankalp** [comment]
@ruddi10 I am still not in favor of changing the requirements.txt because for example if you see the installing dependencies in GitHub workflow build, you will see that there are no problems related to dependency updates.
But If in future other contributors faces this problem I will reopen this issue.

**Comment by codesankalp** [comment]
Which python version are you using?

**Comment by ruddi10** [comment]
3.8.5
